name: prison
version: '1.0'
main: fr.venazia.prison.Main
api-version: '1.20'
authors: [ mynosci ]
depends: [ WorldEdit ]
softdepends:
    - PlaceholderAPI
commands:
    chance:
        description: Commande pour voir la chance
        usage: /chance
        aliases: [prisonchance, chances]
    darkmarket:
        description: NPC pour le marché noir
    acceptquest:
        description: Commande pour accepter une quête
        usage: /acceptquest §c<quête>
        permission: prison.acceptquest
        aliases: [prisonacceptquest, aq, acceptq]
    prestige:
        description: Commande pour monter de prestige
        usage: /prestige
        permission: prison.prestige
        aliases: [prisonprestige, pr, prestige]
    is:
        description: Commande pour voir les informations de ton île
    permile:
        description: Commande pour voir les permissions de ton île
    market:
        description: NPC pour le marché
    voyages:
        aliases:
            - voyage
        permission-message: '§8[§cNPC§8] §cVous devez passer par le NPC §2§lVoyageur §c(au spawn) pour accéder à cette commande.'
    help:
        description: helper
    lore:
        permission: prison.iname
        description: Lore
        aliases: [ilore]
    uptime:
        permission: prison.iname
        description: Uptime du serveur
    iname:
        description: IName
        permission: prison.iname
        aliases: [iname, itemname, itemsname, itemsetname]
    warp:
        description: tp warp
    god:
        permission: prison.iname
        description: GodMode
    createkit:
        description: Commande pour créer un kit
        usage: /createkit §c<kit>
        permission: prison.createkit
        aliases: [prisoncreatekit, ck, createk]
    kit:
        description: Commande pour recevoir un kit
        usage: /kit §c<kit>
        permission: prison.kit
        aliases: [prisonkit, getkit]
    broadcast:
        description: bc
        aliases: [bc, broadcast]
    gamemode:
        description: gm
        permission: prison.staff
        aliases: [gm, gamemode]
    lookup:
        description: lookup
    valeur:
        description: Commande pour voir la valeur d'un bloc
        usage: /valeur §c<bloc>
        aliases: [prisonvaleur, value, values]
    jailconteste:
        permission: prison.admin
    money:
        description: Commande pour voir son argent
        usage: /money
        permission: prison.money
        aliases: [prisonmoney, m, bal]
    rankup:
        description: Commande pour monter de grade
        usage: /rankup
        permission: prison.rankup
        aliases: [prisonrankup, ru, prisonup, up]
    minereset:
        description: Commande pour reset une mine
        usage: /minereset §c<mine>
        permission: prison.minereset
        aliases: [prisonminereset, mr, prisonreset, reset]
    blocksbroken:
        description: Commande pour voir le nombre de blocs cassés
        usage: /blocks
        permission: prison.blocksbroken
        aliases: [prisonblocksbroken, blocksb, bb]
    prison:
        description: Commande principale du plugin Prison
        usage: /prison
        permission: prison.command
        aliases: [prison, prisongest]
    setspawn:
        description: Commande pour définir le spawn de la prison
        usage: /setspawn
        permission: prison.setspawn
        aliases: [setspawn, prisonsetspawn]
    spawn:
        description: Commande pour se téléporter au spawn de la prison
        usage: /spawn
        permission: prison.spawn
        aliases: [spawn, prisonspawn]
    resetmine:
        description: Commande pour reset une mine
        usage: /resetmine
        permission: prison.resetmine
        aliases: [prisonresetmine, prm, prisonreset, resetm]
    setmine:
        description: Commande pour définir une mine
        usage: /setmine
        permission: prison.setmine
        aliases: [prisonsetmine, psm, prisonset, setm]
