# Ce workflow construit un package avec Maven et le publie sur GitHub Packages lors de la création d'une release
# Pour plus d'informations, voir : https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Vérification et upload


on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
