# Ce workflow construit un package avec Maven et le publie sur GitHub Packages lors de la création d'une release
# Pour plus d'informations, voir : https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Vérification et upload


on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and Test Project
        run: mvn -B package --file pom.xml

      - name: Upload to Production Server
        env:
          SFTP_SERVER: 'panel.mynodev.fr'
          SFTP_USER: 'root'
          SFTP_PASSWORD: 'Chipie86**Nathan2010*'
          REMOTE_DIR: '/home/venazia/prison/plugins'
        run: | #runner
          sudo apt-get install -y sshpass
          sshpass -p $SFTP_PASSWORD scp -o StrictHostKeyChecking=no target/prison-dev.jar $SFTP_USER@$SFTP_SERVER:$REMOTE_DIR